DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    first VARCHAR(255) NOT NULL,
    last  VARCHAR(255) NOT NULL,
    mail VARCHAR(512) NOT NULL UNIQUE,
    pass VARCHAR(255) NOT NULL,
    profilepic VARCHAR(512),
    bio VARCHAR(512)
);

DROP TABLE IF EXISTS friendships;

CREATE TABLE friendships (
    id SERIAL PRIMARY KEY,
    requester_id INTEGER NOT NULL,
    receiver_id INTEGER NOT NULL,
    status INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
